# Generated by Django 4.1 on 2023-02-08 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assign_view",
                    models.CharField(
                        choices=[("Лекція", "Лекція"), ("Практика", "Практика")],
                        max_length=15,
                        null=True,
                        verbose_name="Вид заняття",
                    ),
                ),
                ("hours", models.IntegerField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "verbose_name": "Заняття",
                "verbose_name_plural": "Заняття",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.IntegerField(verbose_name="Курс")),
                ("group_name", models.CharField(max_length=100, verbose_name="Группа")),
            ],
            options={
                "verbose_name": "Групи",
                "verbose_name_plural": "Групи",
            },
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "s_name",
                    models.CharField(max_length=20, verbose_name="Коротка назва"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Повна назва")),
            ],
            options={
                "verbose_name": "Дисципліни",
                "verbose_name_plural": "Дисципліни",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s_name", models.CharField(max_length=20, verbose_name="Им'я")),
                ("name", models.CharField(max_length=100, verbose_name="ФИО")),
            ],
            options={
                "verbose_name": "Викладачі",
                "verbose_name_plural": "Викладачі",
            },
        ),
        migrations.CreateModel(
            name="AttendanceClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата проведення")),
                (
                    "hours",
                    models.IntegerField(default=2, verbose_name="Годин проведено"),
                ),
                (
                    "assign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="report.assign",
                        verbose_name="Заняття",
                    ),
                ),
            ],
            options={
                "verbose_name": "Події",
                "verbose_name_plural": "Події",
            },
        ),
        migrations.CreateModel(
            name="AssignTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("09.00 - 10.20", "09.00 - 10.20"),
                            ("10.50 - 12.10", "10.50 - 12.10"),
                            ("12.55 - 14.15", "12.55 - 14.15"),
                            ("14.45 - 16.05", "14.45 - 16.05"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Понеділок", "Понеділок"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                        ],
                        max_length=15,
                    ),
                ),
                ("hour", models.IntegerField(default=2)),
                (
                    "assign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report.assign"
                    ),
                ),
            ],
            options={
                "verbose_name": "подію",
                "verbose_name_plural": "події",
            },
        ),
        migrations.AddField(
            model_name="assign",
            name="discipline",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.discipline",
                verbose_name="Дисципліна",
            ),
        ),
        migrations.AddField(
            model_name="assign",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.course",
                verbose_name="Група",
            ),
        ),
        migrations.AddField(
            model_name="assign",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.teacher",
                verbose_name="Викладач",
            ),
        ),
    ]
