# Generated by Django 4.1 on 2023-02-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assign",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="assign",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
