# Generated by Django 4.1 on 2023-02-08 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_alter_assign_end_date_alter_assign_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceclass",
            name="assign",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.assign",
                verbose_name="Заняття",
            ),
        ),
    ]
