# Generated by Django 4.1 on 2023-02-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0003_alter_attendanceclass_assign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceclass",
            name="hours",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Годин проведено"
            ),
        ),
    ]
