# Generated by Django 4.0 on 2023-01-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_remove_assign_end_date_remove_assign_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign',
            name='day',
        ),
        migrations.AddField(
            model_name='assigntime',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default=None, max_length=15),
            preserve_default=False,
        ),
    ]
