# Generated by Django 4.0 on 2023-01-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_remove_assign_day_assigntime_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceclass',
            name='hours',
            field=models.IntegerField(default=2),
        ),
    ]
