# Generated by Django 4.0 on 2023-01-30 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_attendanceclass_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTotalHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.IntegerField()),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.assign')),
            ],
        ),
    ]
