# Generated by Django 4.0 on 2023-02-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_attendancetotalhours_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetotalhours',
            name='total_hours',
            field=models.IntegerField(),
        ),
    ]
